const poemData = [
    { text: "宋人", py: "sòng rén", zh: "宋国人。", en: "A person from the State of Song." },
    { text: "有", py: "yǒu", zh: "有一个。", en: "There was a" },
    { text: "闵", py: "mǐn", zh: "同“悯”，忧虑、担心。", en: "worrying about", exam: true },
    { text: "其", py: "qí", zh: "他的。", en: "his" },
    { text: "苗", py: "miáo", zh: "禾苗。", en: "seedlings" },
    { text: "之", py: "zhī", zh: "助词，用在主谓之间，取消句子独立性，不译。", en: "particle", exam: true },
    { text: "不长", py: "bù zhǎng", zh: "没有长高。“长”，长高。", en: "not growing taller" },
    { text: "而", py: "ér", zh: "连词，表转折，却、反而。", en: "but" },
    { text: "揠", py: "yà", zh: "拔起。", en: "pulling up", exam: true },
    { text: "之", py: "zhī", zh: "代词，代指禾苗。", en: "them" },
    { text: "者", py: "zhě", zh: "……的人（与前面的“有……者”呼应）。", en: "person," },
    { text: "，", punc: true },
    { text: "芒芒然", py: "máng máng rán", zh: "疲惫不堪、无精打采的样子。", en: "looking exhausted", exam: true },
    { text: "归", py: "guī", zh: "回到家里。", en: "he returned home," },
    { text: "，", punc: true },
    { text: "谓", py: "wèi", zh: "对……说。", en: "and told" },
    { text: "其人", py: "qí rén", zh: "他家里的人。", en: "his family members," },
    { text: "曰", py: "yuē", zh: "说。", en: "saying:" },
    { text: "：“", punc: true },
    { text: "今日", py: "jīnrì", zh: "今天。", en: "Today" },
    { text: "病", py: "bìng", zh: "极度疲劳、累坏了（古汉语中不指生病）。", en: "I am worn out!", exam: true },
    { text: "矣", py: "yǐ", zh: "了（表感叹）。", en: "(particle)" },
    { text: "！", punc: true },
    { text: "予", py: "yǔ", zh: "第一人称代词，我。", en: "I", exam: true },
    { text: "助", py: "zhù", zh: "帮助。", en: "helped" },
    { text: "苗", py: "miáo", zh: "禾苗。", en: "the seedlings" },
    { text: "长", py: "zhǎng", zh: "长高。", en: "grow taller" },
    { text: "矣", py: "yǐ", zh: "了。", en: "indeed!”" },
    { text: "！”", punc: true },
    { text: "其", py: "qí", zh: "他的。", en: "His" },
    { text: "子", py: "zǐ", zh: "儿子。", en: "son" },
    { text: "趋", py: "qū", zh: "小步快走，快步走过去。", en: "hurried", exam: true },
    { text: "而", py: "ér", zh: "连词，表修饰，地。", en: "and" },
    { text: "往", py: "wǎng", zh: "去（田里）。", en: "went" },
    { text: "视", py: "shì", zh: "看，观察。", en: "to look at" },
    { text: "之", py: "zhī", zh: "代词，它们（指禾苗）。", en: "them," },
    { text: "，", punc: true },
    { text: "苗", py: "miáo", zh: "禾苗。", en: "but the seedlings" },
    { text: "则", py: "zé", zh: "已经、却（表转折或既成事实）。", en: "had already" },
    { text: "槁", py: "gǎo", zh: "干枯，枯萎。", en: "withered.", exam: true },
    { text: "矣", py: "yǐ", zh: "了。", en: "(particle)" },
    { text: "。", punc: true },
    { text: "天下", py: "tiān xià", zh: "普天之下，世上。", en: "In the world," },
    { text: "之", py: "zhī", zh: "的。", en: "those who" },
    { text: "不助", py: "bú zhù", zh: "不去帮助。", en: "do not help" },
    { text: "苗", py: "miáo", zh: "禾苗。", en: "the seedlings" },
    { text: "长", py: "zhǎng", zh: "长高。", en: "grow" },
    { text: "者", py: "zhě", zh: "的人。", en: "are" },
    { text: "寡", py: "guǎ", zh: "少，很少。", en: "few.", exam: true },
    { text: "矣", py: "yǐ", zh: "了。", en: "(particle)" },
    { text: "！", punc: true },
    { text: "以为", py: "yǐ wéi", zh: "认为。", en: "Those who think" },
    { text: "无益", py: "wú yì", zh: "没有好处，没有用处。", en: "it is useless" },
    { text: "而", py: "ér", zh: "连词，因而，就。", en: "and" },
    { text: "舍", py: "shě", zh: "放弃，丢下不管。", en: "abandon", exam: true },
    { text: "之", py: "zhī", zh: "它们（指禾苗）。", en: "them," },
    { text: "者", py: "zhě", zh: "的人。", en: "are like those who" },
    { text: "，", punc: true },
    { text: "不耘", py: "bù yún", zh: "不去除草。“耘”，田间除草。", en: "do not weed", exam: true },
    { text: "苗", py: "miáo", zh: "禾苗。", en: "the fields;" },
    { text: "者", py: "zhě", zh: "的人。", en: "person;" },
    { text: "也", py: "yě", zh: "表判断语气。", en: "(particle)" },
    { text: "；", punc: true },
    { text: "助", py: "zhù", zh: "帮助。", en: "those who help" },
    { text: "之", py: "zhī", zh: "它们。", en: "them" },
    { text: "长", py: "zhǎng", zh: "长高。", en: "grow" },
    { text: "者", py: "zhě", zh: "的人。", en: "are like those who" },
    { text: "，", punc: true },
    { text: "揠", py: "yà", zh: "拔苗。", en: "pull up" },
    { text: "苗", py: "miáo", zh: "禾苗。", en: "the seedlings;" },
    { text: "者", py: "zhě", zh: "的人。", en: "person;" },
    { text: "也", py: "yě", zh: "表判断语气。", en: "(particle)" },
    { text: "；", punc: true },
    { text: "非徒", py: "fēi tú", zh: "不仅，不单单。“徒”，仅仅。", en: "not only", exam: true },
    { text: "无益", py: "wú yì", zh: "没有好处。", en: "is it useless," },
    { text: "，", punc: true },
    { text: "而又", py: "ér yòu", zh: "反而、而且又。", en: "but it also" },
    { text: "害", py: "hài", zh: "伤害，害苦。", en: "harms" },
    { text: "之", py: "zhī", zh: "它们（指禾苗）。", en: "them." },
    { text: "。", punc: true }
];
